version: 2.0
jobs:
  build:
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      steps:
        - checkout
        
        - run: mvn dependency:go-offline
        
        - save_cache:
            paths:
              - ~/.m2
        
        - run: mvn clean package docker:build
        
        - store_test_results:
            path: target/surefire-reports
        
        - store_artifacts:
            path: target/photo-capture-0.0.1-SNAPSHOT.jar